FROM gcr.io/dataflow-templates-base/python312-template-launcher-base:latest

ENV FLEX_TEMPLATE_PYTHON_PY_FILE="/template/backend/pipelines/feedback_pipeline.py"
ENV FLEX_TEMPLATE_PYTHON_SETUP_FILE="/template/setup.py"
ENV PIP_NO_DEPS=True

COPY requirements.txt /template/
RUN pip install --no-cache-dir -r /template/requirements.txt

COPY . /template/

ENV PYTHONPATH=/template
