project_id         = "flash-aviary-491923-h1"
region             = "europe-west1"
dataflow_region    = "us-west1"
firestore_location = "nam5"
firestore_database = "auxless"
github_owner       = "pvvishwesh-lang"
github_repo        = "AuxLess"
