name: Auto Merge

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          squash-title: true
          labels: automerge
